import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createCustomerAccount } from "@/app/actions";
import { Topbar } from "@/app/components/topbar";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: profile } = await supabase.from("profiles").select("role,full_name").eq("id", user.id).single(); if (profile?.role !== "admin") redirect("/dashboard");
  const { data: accounts = [] } = await supabase.from("profiles").select("id,full_name,role,organizations(name)").order("created_at", { ascending: false });
  return <div className="shell"><Topbar name={profile.full_name} role="admin" /><main className="page"><div className="title-row"><div><div className="eyebrow">Administrator</div><h1>Accounts</h1><p className="subtle">Provision customer or admin access, then work in any customer’s pipeline.</p></div></div><div className="admin-layout"><section className="panel"><h2>Create an account</h2><p className="subtle">Customer creates an organization and first login together; admins are platform-wide.</p><form action={createCustomerAccount} style={{marginTop:20}}><div className="form-grid"><label className="field full">Account type<select className="select" name="role" defaultValue="customer"><option value="customer">Customer</option><option value="admin">Administrator</option></select></label><label className="field full">Customer company <span className="subtle">(required for customers)</span><input className="input" name="organization_name" placeholder="Acme Ltd" /></label><label className="field">Contact name<input className="input" name="full_name" placeholder="Jamie Chen" /></label><label className="field">Work email<input className="input" required type="email" name="email" placeholder="jamie@acme.com" /></label><label className="field full">Temporary password<input className="input" required minLength={8} type="password" name="password" placeholder="At least 8 characters" /></label></div><div className="form-actions"><button className="btn">Create account</button></div></form><p className="subtle" style={{marginTop:16}}>Requires <code>SUPABASE_SERVICE_ROLE_KEY</code> in your local/Vercel environment. It remains server-only.</p></section><section className="panel"><h2>People with access</h2><p className="subtle">Admin accounts can work in every customer’s pipeline.</p><div style={{marginTop:12}}>{accounts.map((account) => <div className="account-row" key={account.id}><div><strong>{account.full_name || "Unnamed user"}</strong><div className="subtle">{(account.organizations as unknown as { name: string } | null)?.name || "Platform administrator"}</div></div><span className="pill">{account.role}</span></div>)}</div></section></div></main></div>;
}
